---
# These tasks are to install Satellite through the CLI including answer files.

- name: SATELLITE | Install Satellite | Load Satellite answer file varriables
  include_vars: file=defaults/answer-file.yml

- name: SATELLITE | Install Satellite | Verify Foreman exists
  stat:
    path: /etc/init.d/foreman
  register: foreman_location

- name: SATELLITE | Install Satellite | Copy satellite answers file to target
  copy:
    src: templates/satellite-answers.yaml
    dest: /etc/foreman-installer/scenarios.d/custom-sat-answers.yaml
  when: foreman_location.stat.exists

- name: SATELLITE | Install Satellite | Update target Satellite answers file
  replace: dest=/etc/foreman-installer/scenarios.d/custom-sat-answers.yaml regexp={{ item.regex }} replace={{ item.setting }}
  with_items: "{{ answer_file_settings }}"
  when: foreman_location.stat.exists

- name: SATELLITE | Install Satellite | Change default satellite answers file location to custom-sat-answers.yaml
  replace: dest=/etc/foreman-installer/scenarios.d/satellite.yaml regexp='satellite-answers.yaml' replace=custom-sat-answers.yaml
  when: foreman_location.stat.exists

- name: SATELLITE | Install Satellite | Configure and start Satellite
  command: /usr/sbin/satellite-installer --scenario "{{ satellite_scenario }}"
  when: foreman_location.stat.exists
  tags:
  - install_satellite

