---
- name: SATELLITE | Lifecycles | Load Hammer varriables
  include_vars: file=defaults/hammer-vars.yml

- name: SATELLITE | Lifecycles | Foreman is running
  shell: 'systemctl is-active foreman-tasks.service'
  register: foreman_status

- name: SATELLITE | Lifecycles | Create Satellite Lifecycle Environments
  command: hammer --password {{ sat_password }} lifecycle-environment create --name "{{ item.name }}" --description "{{ item.description }}" --organization "{{ satellite_organization }}" --prior "{{ item.prior }}"
  with_items: "{{ lifecycle_names }}"
  when: foreman_status.stdout == "active"

