---
- name: SATELLITE | Registration | Get Satellite pool ID
  shell: /usr/bin/subscription-manager list --all --available --matches="*Satellite*" | awk '/Pool ID/ {print $3}' | head -1
  tags:
    - rhn
  register: pool_id
  ignore_errors: yes

#Attaching the system to the right Pool
- name: SATELLITE | Registration | Attach machine with Satellite pool ID
  command: /usr/bin/subscription-manager attach --pool={{ pool_id.stdout }}
  tags:
    - rhn
  ignore_errors: yes
