---
- name: SATELLITE | Manifest | Load Hammer varriables
  include_vars: file=defaults/hammer-vars.yml

- name: SATELLITE | Manifest | Foreman is running
  shell: 'systemctl is-active foreman-tasks.service'
  register: foreman_status

- name: SATELLITE | Manifest | Copy mainfiest file to Satellite server
  copy:
    src: files/{{ manifest_filename }}
    dest: /root/{{ manifest_filename }}
    mode: 0644
    owner: root
    group: root
  when: foreman_status.stdout == "active"

- name: SATELLITE | Manifest | Uplaod manifest to Satellite server
  command: hammer --password {{ sat_password }} subscription upload --organization {{ satellite_organization }} --file /root/{{ manifest_filename }}
  when: foreman_status.stdout == "active"

